### ISSUE TITLE
PrePrint .pdf link does not seem to be available

### ISSUE THREAD

**Issue by ghost** [richard-roberts/Toward-Virtual-Machine-Adaption-Rather-than-Reimplementation#1]
Hello.

The main readme has a link to a .pdf but clicking
on it yields a "302, Page Not Found â‡¦" error -
not sure what the weird terminating token is ...

Has the .pdf been moved since then?

**Comment by smarr** [comment]
Looks like it, @richard-roberts? Meanwhile, here is another copy: http://stefan-marr.de/downloads/morevms17-roberts-et-al-toward-virtual-machine-adaption.pdf

**Comment by ghost** [comment]
Hi there,

Thanks for letting us know and apologies that the preprint wasn't accessible. I've fixed the broken link and also added a link to the workshop where we presented the paper.  Feel free to contact me directly with any questions on the paper :)
